config/routes.rb
ChouetteIhm::Application.routes.draw do

  # ====> Beware not to use /healtcheck route : already used by MiddlewareHealthcheck

  devise_for :users, :controllers => {
    :registrations => 'users/registrations', :invitations => 'users/invitations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'referentials#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      get '/additionnal_fields', to: 'users#additionnal_fields'
      post '/save_additionnal_fields', to: 'users#save_additionnal_fields'
    end
    
  end

  namespace :api do
    namespace :v1 do
      resources :time_tables, :only => [:index, :show]
      resources :connection_links, :only => [:index, :show]
      resources :companies, :only => [:index, :show]
      resources :networks, :only => [:index, :show]
      resources :stop_areas, :only => [:index, :show]
      resources :group_of_lines, :only => [:index, :show]
      resources :access_points, :only => [:index, :show]
      resources :access_links, :only => [:index, :show]
      resources :lines, :only => [:index, :show] do
        resources :journey_patterns, :only => [:index, :show]
        resources :routes, :only => [:index, :show] do
          resources :vehicle_journeys, :only => [:index, :show]
          resources :journey_patterns, :only => [:index, :show]
          resources :stop_areas, :only => [:index, :show]
        end
      end
      resources :routes, :only => :show
      resources :journey_patterns, :only => :show
      resources :vehicle_journeys, :only => :show
    end
  end

  resource :organisation, :only => [:show, :edit, :update] do
    resources :users
    get '/role/edit/:id', to: 'users#role_edit', as: 'user_role_edit'
    patch '/role/update/:id', to: 'users#role_update', as: 'user_role_update'
    resources :rule_parameter_sets
  end

  resources :referentials do
    resources :api_keys
    resources :autocomplete_stop_areas
    resources :autocomplete_time_tables
    resources :autocomplete_route_sections
    resources :autocomplete_timebands
    resources :group_of_lines do
      collection do
        get 'name_filter'
      end
    end

    resources :networks

    resources :lines do
      delete :index, on: :collection, action: :delete_all
      collection do
        get 'name_filter'
      end
      resources :routes do
        member do
          get 'edit_boarding_alighting'
          put 'save_boarding_alighting'
        end
        resources :journey_patterns do
          member do
            get 'new_vehicle_journey'
          end
          resource :route_sections_selector, path: 'sections' do
            post 'selection'
          end
        end
        resources :vehicle_journeys, :vehicle_journey_frequencies do
          get 'select_journey_pattern', :on => :member
          resources :vehicle_translations
          resources :time_tables
        end
        resources :vehicle_journey_imports
        resources :vehicle_journey_exports
      end
    end

    resources :import_tasks, :only => [:new, :create]
    resources :imports, :only => [:index, :show, :destroy] do
      member do
        get "imported_file"
        get "rule_parameter_set"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :export_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :exports, :only => [:index, :show, :destroy]  do
      member do
        get "exported_file"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :compliance_check_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :compliance_checks, :only => [:index, :show, :destroy] do
      member do
        get 'export', defaults: { format: 'zip' }
        get 'report'
        get 'progress'
        get 'rule_parameter_set'
        get 'download_validation'
      end
      collection do
        get 'references'
      end
    end

    resources :companies

    resources :time_tables do
      collection do
        get :tags
      end
      member do
        get 'duplicate'
      end
      resources :time_table_dates
      resources :time_table_periods
      resources :time_table_combinations
    end

    resources :timebands

    resources :access_points do
       resources :access_links
    end

    resources :stop_areas do
      resources :access_points do
        resources :access_links
      end
      resources :stop_area_copies
      resources :stop_area_routing_lines
      member do
        get 'add_children'
        get 'select_parent'
        get 'add_routing_lines'
        get 'add_routing_stops'
        get 'access_links'
      end
      collection do
        put 'default_geometry'
      end
    end

    resources :connection_links do
      resources :stop_areas
      member do
        get 'select_areas'
      end
    end
    resources :clean_ups

    resources :route_sections do
      collection  do
        get 'create_to_edit'
      end
    end
  end
  root :to => "referentials#index"

  get '/statistics', :to => 'statistics#index'
  get '/statistics/export', :to => 'statistics#export'

  get '/help/(*slug)' => 'help#show'

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

end

app/controllers/time_tables_controller.rb
class TimeTablesController < ChouetteController
  before_action :check_authorize, except: [:show, :index, :tags]

  include TimeTablesHelper
  defaults :resource_class => Chouette::TimeTable
  respond_to :html
  respond_to :xml
  respond_to :json
  respond_to :js, :only => :index

  belongs_to :referential

  def show

    @year = params[:year] ? params[:year].to_i : Date.today.cwyear
    @time_table_combination = TimeTableCombination.new
    show! do
      build_breadcrumb :show
    end
  end

  def new
    @autocomplete_items = ActsAsTaggableOn::Tag.all
    new! do
      build_breadcrumb :new
    end
  end

  def edit
    edit! do
      build_breadcrumb :edit
      @autocomplete_items = ActsAsTaggableOn::Tag.all
    end
  end

  def index
    request.format.kml? ? @per_page = nil : @per_page = 12

    index! do |format|
      format.html {
        if collection.out_of_range? && params[:page].to_i > 1
          redirect_to url_for params.merge(:page => 1)
          return
        end
        build_breadcrumb :index
      }
    end
  end

  def duplicate
    @time_table = Chouette::TimeTable.find params[:id]
    # prepare breadcrumb before prepare data for new timetable
    build_breadcrumb :edit
    @time_table = @time_table.duplicate
    render :new
  end

  def tags
    @tags = ActsAsTaggableOn::Tag.where("tags.name LIKE ?", "%#{params[:tag]}%")
    respond_to do |format|
      format.json { render :json => @tags.map{|t| {:id => t.id, :name => t.name }} }
    end
  end

  protected

  def collection
    ransack_params = params[:q]
    # Hack to delete params can't be used by ransack
    tag_search = ransack_params["tag_search"].split(",").collect(&:strip) if ransack_params.present? && ransack_params["tag_search"].present?
    ransack_params.delete("tag_search") if ransack_params.present?

    selected_time_tables = tag_search ? select_time_tables.tagged_with(tag_search, :wild => true, :any => true) : select_time_tables
    @q = selected_time_tables.ransack(ransack_params)
    @time_tables ||= @q.result(:distinct => true).order(:comment).page(params[:page])
  end

  def select_time_tables
    if params[:route_id]
      referential.time_tables.joins( vehicle_journeys: :route).where( "routes.id IN (#{params[:route_id]})")
   else
      referential.time_tables
   end
  end

  def resource_url(time_table = nil)
    referential_time_table_path(referential, time_table || resource)
  end

  def collection_url
    referential_time_tables_path(referential)
  end

  private

  def time_table_params
    params.require(:time_table).permit( :objectid, :object_version, :creation_time, :creator_id, :version, :comment, :int_day_types, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :start_date, :end_date, { :dates_attributes => [:date, :in_out, :id, :_destroy] }, { :periods_attributes => [:period_start, :period_end, :_destroy, :id] }, :tag_list, :tag_search )
  end
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/views/time_tables/_date_fields.erb
<%= f.inputs :class => 'nested-fields date' do %>
  <%= f.label @time_table.human_attribute_name("date"), :class => 'col-md-1' %>
  <%= f.input :date, :as => :date_picker, :label => false, :input_html => { :class => 'form-control col-md-3' }%>
  <%= f.input :in_out, :as => :hidden, :input_html => {:value => true} %>
  <%= link_to_remove_association t('actions.destroy'), f, :class => "col-md-3" %>
<% end %>

app/views/time_tables/_dates.html.erb
  <ul class='dates'>
    <% @time_table.dates.where("in_out = true").to_a.each do |tmd| %>
    <li class="<%= (tmd.position%2==0) ? 'odd' : 'even' %>"><%= l tmd.date %>
    </li>
    <% end %>
  </ul>

app/views/time_tables/_excluded_dates.html.erb
  <ul class='dates'>
    <% @time_table.dates.where("in_out = false").to_a.each do |tmd| %>
    <li class="<%= (tmd.position%2==0) ? 'odd' : 'even' %>"><%= l tmd.date %>
    </li>
    <% end %>
  </ul>

app/views/time_tables/_form.erb
<%= semantic_form_for [@referential, @time_table] do |form| %>
  <%= form.inputs do %>
    <%= form.input :comment, :input_html => { :title => t("formtastic.titles#{format_restriction_for_locales(@referential)}.time_table.comment")} %>
    <%= form.input :version %>
    <%= form.input :tag_search, :as => :tags, :input_html => { :id => "tag_search",:placeholder => t("formtastic.placeholders.time_table.tag_search") } %>
    <%= form.input :tag_list, :as => :hidden, :input_html => { :id => "tag_list" } %>

    <%= form.input :objectid, :required => !@time_table.new_record?, :input_html => { :title => t("formtastic.titles#{format_restriction_for_locales(@referential)}.time_table.objectid")} %>
    <%= form.input :start_date, :as => :date_picker %>
    <%= form.input :end_date, :as => :date_picker %>
  <% end %>

  <h3 class="time_table_periods"><%= @time_table.human_attribute_name("periods") %></h3>
  <div id="periods_content">
	  <%= form.inputs :class => 'day_type' do %>
	    <label class="day_type_label"><%= @time_table.human_attribute_name("day_types") %></label>
	    <%= form.input :monday, :as => :boolean, :class => "others" %>
	    <%= form.input :tuesday, :as => :boolean %>
	    <%= form.input :wednesday, :as => :boolean %>
	    <%= form.input :thursday, :as => :boolean %>
	    <%= form.input :friday, :as => :boolean %>
	    <%= form.input :saturday, :as => :boolean %>
	    <%= form.input :sunday, :as => :boolean %>
	  <% end %>
	  <div id="periods">
		  <%= form.semantic_fields_for :periods do |p| %>
		     <%= render "period_fields",  :f => p %>
		  <% end %>
	  </div>
	  <%= link_to_add_association t("time_tables.actions.add_period"), form, :periods ,
	  :"data-association-insertion-method" => "append",
	  :"data-association-insertion-node" => "div#periods"%>
  </div>

  <h3 class="time_table_dates"><%= @time_table.human_attribute_name("dates") %></h3>
  <div id="dates_content">
    <div id="dates">
		  <%= form.semantic_fields_for :dates, @time_table.dates.to_a.select {|d| d.in_out == true}  do |p| %>
	  	<%= render "date_fields",  :f => p %>
		  <% end %>
	  </div>
	  <%= link_to_add_association t("time_tables.actions.add_date"), form, :dates ,
	      :"data-association-insertion-method" => "append",
	  :"partial" => "date_fields",
	  :"data-association-insertion-node" => "div#dates" %>
  </div>

  <h3 class="time_table_dates"><%= @time_table.human_attribute_name("excluded_dates") %></h3>
  <div id="excluded_dates_content">
	  <div id="excluded_dates">
		  <%= form.semantic_fields_for :dates, @time_table.dates.to_a.select {|d| d.in_out == false}  do |p| %>
		  <%= render "excluded_date_fields",  :f => p %>
		  <% end %>
	  </div>
	  <%= link_to_add_association t("time_tables.actions.add_excluded_date"), form, :dates ,
	  :"data-association-insertion-method" => "append",
	  :"partial" => "excluded_date_fields",
	  :"data-association-insertion-node" => "div#excluded_dates" %>
  </div>

  <%= form.actions do %>
    <%= form.action :submit, :as => :button %>
    <%= form.action :cancel, :as => :link %>
  <% end %>
<% end %>

<%= javascript_tag "var items = #{ @time_table.tag_list.to_a };" %>

<script>
  $("#tag_search").tagsManager(
  {
    prefilled: items,
    output: '#tag_list',
    tagsContainer: '#tagsContainer'
  });

  var time_tables_tag_list = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: '<%= tags_referential_time_tables_path(@referential, :format => 'json') %>?tag=%QUERY',
  });

  time_tables_tag_list.initialize();

  $("#tag_search").typeahead(null, {
    name: 'time_tables_tag_list',
    displayKey: 'name',
    source: time_tables_tag_list.ttAdapter()
  });

</script>

app/views/time_tables/_period_fields.erb
<%= f.inputs :class => 'nested-fields period' do %>
  <%= f.label @time_table.human_attribute_name("period_start"), :class => "col-md-1" %>
  <%= f.input :period_start, :as => :date_picker, :label => false, :input_html => { :class => 'form-control col-md-3' }%>
    <%= f.label @time_table.human_attribute_name("period_end"), :class => "col-md-1" %>       
  <%= f.input :period_end, :as => :date_picker, :label => false, :input_html => { :class => 'form-control col-md-3' }%>
  <%= link_to_remove_association t('actions.destroy'), f, :class => "col-md-2" %>
<% end %>

app/views/time_tables/_properties_show.html.erb
<div class="time_table_show">

  <div class="resume">
    <div class="validity <%= time_table_state_code(@time_table) %>"></div>
    <label>
      <% if @time_table.bounding_dates.empty? %>
        <%= t(".resume_empty") %>
      <% else %>
        <%= t(".resume", :start_date => l(@time_table.bounding_dates.min),
                   :end_date => l(@time_table.bounding_dates.max)) %>
      <% end %>
    </label>
  </div>
  <div class="summary">
    <p>
      <label><%= @time_table.human_attribute_name("version") %>: </label>
      <%= @time_table.version %>
    </p>
    <p>
      <label><%= @time_table.human_attribute_name("tag_list") %>: </label>
      <%= @time_table.tag_list %>
    </p>
    <p>
      <label><%= @time_table.human_attribute_name("day_types") %>:&nbsp;&nbsp;</label>
      <% if @time_table.int_day_types & 508 == 0 %>
        <label><%= @time_table.human_attribute_name("none") %></label>
      <% else %>
	      <% if @time_table.monday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("monday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.tuesday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("tuesday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.wednesday %>
	        <span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("wednesday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.thursday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("thursday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.friday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("friday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.saturday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("saturday") %>&nbsp;</span>
	      <% end %>

	      <% if @time_table.sunday %>
	      	<span class='day_type'>&nbsp;<%= @time_table.human_attribute_name("sunday") %>&nbsp;</span>
	      <% end %>
      <% end %>
    </p>

  <h3 class="time_table_calendars">
	<a class="calendars"><%= @time_table.human_attribute_name("calendars") %>
      <%= image_tag("icons/plus.png"  , :class => "switcher", :style => "display: none;") %>
      <%= image_tag("icons/minus.png"  , :class => "switcher" ) %>
    </a>

  </h3>
  <div class="calendars content">
    <div class="year_choice">
      <span class="previous"> <%= link_to("<", referential_time_table_path(@referential, @time_table, :year => (@year - 1)) ) %> </span>
      <span class="year"> <%= "#{@year}" %> </span>
      <span class="next"> <%= link_to(">", referential_time_table_path(@referential, @time_table, :year => (@year + 1)) ) %> </span>
    </div>
    <div class="calendar_helper">
    <%= cal = ""
      (1..12).each do |month|
        cal << calendar(:year => @year, :month => month, :first_day_of_week => 1) do |d|
                 if @time_table.excluded_date?(d)
                   [link_to(d.mday, edit_referential_time_table_path(@referential, @time_table) ), {:class => "excluded_date"}]
                 elsif @time_table.include_in_overlap_dates?(d)
                   [link_to(d.mday, edit_referential_time_table_path(@referential, @time_table) ), {:class => "overlap_date"}]
                 elsif @time_table.include_in_dates?(d)
                   [link_to(d.mday, edit_referential_time_table_path(@referential, @time_table) ), {:class => "selected_date"}]
                 elsif @time_table.include_in_periods?(d)
                   [link_to(d.mday, edit_referential_time_table_path(@referential, @time_table) ), {:class => "selected_period"}]
                 end
               end
      end
      cal.html_safe
    %>
    </div>
  </div>


  </div>
  <h3 class="time_table_periods">
	<a class="periods"><%= @time_table.human_attribute_name("periods") %>
      <%= image_tag("icons/plus.png"  , :class => "switcher", :style => "display: none;") %>
      <%= image_tag("icons/minus.png"  , :class => "switcher" ) %>
    </a>

  </h3>
  <div class="periods content">
  	<%= render "time_tables/periods" %>
  </div>

  <h3 class="time_table_dates">
	<a class="dates"><%= @time_table.human_attribute_name("dates") %>
      <%= image_tag("icons/plus.png"  , :class => "switcher", :style => "display: none;") %>
      <%= image_tag("icons/minus.png"  , :class => "switcher" ) %>
    </a>
  </h3>

  <div class="dates content">
  	<%= render "time_tables/dates" %>
  </div>

  <h3 class="time_table_dates">
	<a class="excluded_dates"><%= @time_table.human_attribute_name("excluded_dates") %>
      <%= image_tag("icons/plus.png"  , :class => "switcher", :style => "display: none;") %>
      <%= image_tag("icons/minus.png"  , :class => "switcher" ) %>
    </a>
  </h3>

  <div class="excluded_dates content">
  	<%= render "time_tables/excluded_dates" %>
  </div>

</div>

app/views/time_tables/_show_time_table.html.erb
<div class="time_table_show" id="time_table_show">
  <p>
    <span class="state-code <%= @time_table.presenter.time_table_state_code %>"><i class="fa fa-certificate"></i></span>
    <label>
      <% if @time_table.bounding_dates.empty? %>
        <%= t(".resume_empty") %>
      <% else %>
        <%= t(".resume", :start_date => l(@time_table.bounding_dates.min), :end_date => l(@time_table.bounding_dates.max)) %>
      <% end %>
    </label>
  </p>
  <p>
    <label><%= @time_table.human_attribute_name("tag_list") %>: </label>
    <%= @time_table.tag_list %>
  </p>
  <p>
    <label>Timetable validity dates:</label>
    <%= @time_table.start_date %> - <%= @time_table.end_date %>
  </p>
  <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#time_tables" data-toggle="tab"><%= @time_table.human_attribute_name("calendars") %></a></li>
    <li><a href="#time_tables_datas" data-toggle="tab"><%= @time_table.human_attribute_name("calendar_details") %></a></li>
  </ul>
  <div id="my-tab-content" class="tab-content">
    <div class="tab-pane active" id="time_tables">
      <div class="well legend">
        <span class="title"><%= t(".legend") %></span>
        <span class="label excluded_date">X</span><%= t(".excluded_date") %>
        <span class="label overlaped_date">X</span><%= t(".overlap_date") %>
        <span class="label selected_date">X</span><%= t(".selected_date") %>
        <span class="label selected_period">X</span><%= t(".selected_period") %>
      </div>
      <div id="calendars">
        <div class="year_choice">
          <span class="previous"> <%= link_to("<", referential_time_table_path(@referential, @time_table, :year => (@year - 1)) ) %> </span>
          <span class="year"> <%= "#{@year}" %> </span>
          <span class="next"> <%= link_to(">", referential_time_table_path(@referential, @time_table, :year => (@year + 1)) ) %> </span>
        </div>
        <div class="calendar_helper">
          <%=
            cal = ""
            (1..12).each do |month|
              cal << calendar(:year => @year, :month => month, :first_day_of_week => 1) do |d|
                class_names = ['day']
                if @time_table.excluded_date?(d)
                  class_names << 'excluded_date'
                elsif @time_table.include_in_overlap_dates?(d)
                  class_names << 'overlaped_date'
                elsif @time_table.include_in_dates?(d)
                  class_names << 'selected_date'
                elsif @time_table.include_in_periods?(d)
                  class_names << 'selected_period'
                else
                  next
                end
                [
                  (
                    policy(:application).write? ?
                    link_to(d.mday, edit_referential_time_table_path(@referential, @time_table)) :
                    d.mday
                  ),
                  { class: class_names.join(' ') }
                ]
              end
            end
            cal.html_safe
          %>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="time_tables_datas">
      <div class="summary">
        <p>
          <label><%= @time_table.human_attribute_name("version") %>: </label>
          <%= @time_table.version %>
        </p>
        <p>
          <label><%= @time_table.human_attribute_name("day_types") %>:&nbsp;&nbsp;</label>
          <% if @time_table.int_day_types & 508 == 0 %>
          <label><%= @time_table.human_attribute_name("none") %></label>
          <% else %>
	          <% %w(monday tuesday wednesday thursday friday saturday sunday).each do |day_type| %>
              <span class="<%= @time_table.send( day_type) ? "included_day_type" : "excluded_day_type" %>">
                <%= @time_table.human_attribute_name(day_type) %>
              </span>
            <% end %>
          <% end %>
        </p>

      </div>

      <% if @time_table.periods.present? %>
      <h3 class="time_table_periods"><%= @time_table.human_attribute_name("periods") %></h3>
      <div class="periods content">
  	    <%= render "time_tables/periods" %>
      </div>
      <% end %>

      <% if @time_table.dates.where("in_out = true").present? %>
      <h3 class="time_table_dates"><%= @time_table.human_attribute_name("dates") %></h3>
      <div class="dates content">
  	    <%= render "time_tables/dates" %>
      </div>
      <% end %>

      <% if @time_table.dates.where("in_out = false").present? %>
      <h3 class="time_table_dates"><%= @time_table.human_attribute_name("excluded_dates") %></h3>
      <div class="excluded_dates content">
  	    <%= render "time_tables/excluded_dates" %>
      </div>
      <% end %>

    </div>
  </div>

</div>

app/views/time_tables/_time_table.html.erb
<div id="index_item" class="panel panel-default time_table">
  <div class="panel-heading">
    <div class="panel-title clearfix">
      <% if policy(:application).write? %>
        <span class="pull-right">
          <%= link_to edit_referential_time_table_path(@referential, time_table), :class => "btn btn-default btn-sm" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to('<span class="fa fa-trash-o"></span>'.html_safe, referential_time_table_path(@referential, time_table), :method => :delete, :data => {:confirm =>  t('time_tables.actions.destroy_confirm')}, :class => "btn btn-danger btn-sm") if delete %>
        </span>
      <% end %>
      <h5>
        <%= link_to([@referential, time_table], :class => "preview", :title => "#{Chouette::TimeTable.model_name.human.capitalize} #{time_table.comment}") do %>
        <span class="state-code <%= time_table.presenter.time_table_state_code %>"><i class="fa fa-certificate"></i></span>
        <span class="name">
          <%= time_table.comment %>
        </span>
        <% end %>
      </h5>
    </div>
  </div>
  <div class="panel-body">
    <%= time_table.presenter.time_tables_shortest_info %>
    <% unless time_table.periods.empty? %>
      <div>
      <% %w(monday tuesday wednesday thursday friday saturday sunday).each do |day_type| %>
        <span class="<%= time_table.send( day_type) ? "included_day_type" : "excluded_day_type" %>">
          <%= time_table.human_attribute_name(day_type).first(2) %>
        </span>
      <% end %>
      </div>
    <% end %>
    <% unless time_table.tags.empty? %>
      <div><%= time_table.presenter.tag_list_shortened %></div>
    <% end %>
  </div>
</div>

app/views/time_tables/_time_tables.html.erb
<div class="page_info">
  <span class="search"> <%= t("will_paginate.page_entries_info.search") %></span> <%= page_entries_info @time_tables %>
</div>
<div class="time_tables paginated_content">
  <%= paginated_content(@time_tables) %>
</div>

<%= render 'shared/paginate', { datas: @time_tables } %>

app/views/time_tables/edit.html.erb
<%= title_tag t('time_tables.edit.title', :time_table => @time_table.comment) %>

<%= render "form" %>

app/views/time_tables/index.html.erb
<%= title_tag t('time_tables.index.title') %>

<%= search_form_for @q, :url => referential_time_tables_path(@referential), remote: true, :html => {:method => :get, class: "form-inline", :id => "search", role: "form"} do |f| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="input-group col-md-9">
      <%= f.text_field :comment_cont, :placeholder => "#{t('.comment')}", :class => 'form-control' %>

      <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
      </div>
    </div><!-- /input-group -->
    <a data-toggle="collapse" data-parent="#search" href="#advanced_search">
      <i class="fa fa-plus"></i> <%= "#{t('.advanced_search')}" %>
    </a>
  </div>

  <div id="advanced_search" class="panel-collapse collapse">
    <div class="panel-body">
      <div>
        <label><%= "#{t('.from')}" %></label>
        <%= f.text_field :start_date_gteq, :placeholder => "#{t('.start_date')}", :class => 'form-control date_picker', :type => "date" %>
        <label><%= "#{t('.to')}" %></label>
        <%= f.text_field :end_date_lteq, :placeholder => "#{t('.end_date')}", :class => 'form-control date_picker', :type => "date" %>
      </div>
      <div>
        <%= f.text_field :tag_search, :placeholder => "#{t('.tag_search')}", :class => 'form-control' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div id="time_tables"><%= render 'time_tables' %></div>


<% content_for :sidebar do %>
<ul class="actions">
  <li><%= link_to t('time_tables.actions.new'), new_referential_time_table_path(@referential), :class => "add" %></li>
  <br>
</ul>
<% end %>

app/views/time_tables/index.js.erb
$('#time_tables').html('<%= escape_javascript(render("time_tables")) %>');

app/views/time_tables/new.html.erb
<%= title_tag t('time_tables.new.title') %>

<%= render "form" %>

app/views/time_tables/show.html.erb
<% require 'calendar_helper' %>

<%= title_tag t('time_tables.show.title', :time_table => @time_table.comment )%>

<%= render "time_table_combinations/combine" %>

<%= render "show_time_table" %>

<% content_for :sidebar do %>
<ul class="actions">
  <li><%= link_to t('time_tables.actions.new'), new_referential_time_table_path(@referential), :class => "add" %></li>
  <li><%= link_to t('time_tables.actions.edit'), edit_referential_time_table_path(@referential, @time_table), :class => "edit" %></li>
  <li><%= link_to t('time_tables.actions.destroy'), referential_time_table_path(@referential, @time_table), :method => :delete, :data => {:confirm =>  t('time_tables.actions.destroy_confirm')}, :class => "remove" %></li>
  <li><%= link_to t('time_tables.actions.duplicate'), duplicate_referential_time_table_path(@referential, @time_table), :class => "clone" %></li>
  <li><%= link_to t('time_tables.actions.combine'), new_referential_time_table_time_table_combination_path(@referential, @time_table), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal_combine', :class => "merge"} %></li>
</ul>


  <%= creation_tag(@time_table) %>
<% end %>