config/routes.rb
ChouetteIhm::Application.routes.draw do

  # ====> Beware not to use /healtcheck route : already used by MiddlewareHealthcheck

  devise_for :users, :controllers => {
    :registrations => 'users/registrations', :invitations => 'users/invitations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'referentials#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      get '/additionnal_fields', to: 'users#additionnal_fields'
      post '/save_additionnal_fields', to: 'users#save_additionnal_fields'
    end
    
  end

  namespace :api do
    namespace :v1 do
      resources :time_tables, :only => [:index, :show]
      resources :connection_links, :only => [:index, :show]
      resources :companies, :only => [:index, :show]
      resources :networks, :only => [:index, :show]
      resources :stop_areas, :only => [:index, :show]
      resources :group_of_lines, :only => [:index, :show]
      resources :access_points, :only => [:index, :show]
      resources :access_links, :only => [:index, :show]
      resources :lines, :only => [:index, :show] do
        resources :journey_patterns, :only => [:index, :show]
        resources :routes, :only => [:index, :show] do
          resources :vehicle_journeys, :only => [:index, :show]
          resources :journey_patterns, :only => [:index, :show]
          resources :stop_areas, :only => [:index, :show]
        end
      end
      resources :routes, :only => :show
      resources :journey_patterns, :only => :show
      resources :vehicle_journeys, :only => :show
    end
  end

  resource :organisation, :only => [:show, :edit, :update] do
    resources :users
    get '/role/edit/:id', to: 'users#role_edit', as: 'user_role_edit'
    patch '/role/update/:id', to: 'users#role_update', as: 'user_role_update'
    resources :rule_parameter_sets
  end

  resources :referentials do
    resources :api_keys
    resources :autocomplete_stop_areas
    resources :autocomplete_time_tables
    resources :autocomplete_route_sections
    resources :autocomplete_timebands
    resources :group_of_lines do
      collection do
        get 'name_filter'
      end
    end

    resources :networks

    resources :lines do
      delete :index, on: :collection, action: :delete_all
      collection do
        get 'name_filter'
      end
      resources :routes do
        member do
          get 'edit_boarding_alighting'
          put 'save_boarding_alighting'
        end
        resources :journey_patterns do
          member do
            get 'new_vehicle_journey'
          end
          resource :route_sections_selector, path: 'sections' do
            post 'selection'
          end
        end
        resources :vehicle_journeys, :vehicle_journey_frequencies do
          get 'select_journey_pattern', :on => :member
          resources :vehicle_translations
          resources :time_tables
        end
        resources :vehicle_journey_imports
        resources :vehicle_journey_exports
      end
    end

    resources :import_tasks, :only => [:new, :create]
    resources :imports, :only => [:index, :show, :destroy] do
      member do
        get "imported_file"
        get "rule_parameter_set"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :export_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :exports, :only => [:index, :show, :destroy]  do
      member do
        get "exported_file"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :compliance_check_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :compliance_checks, :only => [:index, :show, :destroy] do
      member do
        get 'export', defaults: { format: 'zip' }
        get 'report'
        get 'progress'
        get 'rule_parameter_set'
        get 'download_validation'
      end
      collection do
        get 'references'
      end
    end

    resources :companies

    resources :time_tables do
      collection do
        get :tags
      end
      member do
        get 'duplicate'
      end
      resources :time_table_dates
      resources :time_table_periods
      resources :time_table_combinations
    end

    resources :timebands

    resources :access_points do
       resources :access_links
    end

    resources :stop_areas do
      resources :access_points do
        resources :access_links
      end
      resources :stop_area_copies
      resources :stop_area_routing_lines
      member do
        get 'add_children'
        get 'select_parent'
        get 'add_routing_lines'
        get 'add_routing_stops'
        get 'access_links'
      end
      collection do
        put 'default_geometry'
      end
    end

    resources :connection_links do
      resources :stop_areas
      member do
        get 'select_areas'
      end
    end
    resources :clean_ups

    resources :route_sections do
      collection  do
        get 'create_to_edit'
      end
    end
  end
  root :to => "referentials#index"

  get '/statistics', :to => 'statistics#index'
  get '/statistics/export', :to => 'statistics#export'

  get '/help/(*slug)' => 'help#show'

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

end

app/models/import_task.rb
require "zip"

class ImportTask
  extend Enumerize
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::Validations
  include ActiveModel::Conversion

  # TODO : Move in configuration
  @@root = "#{Rails.root}/tmp/imports"
  cattr_accessor :root

  enumerize :data_format, in: %w( neptune netex netexprofile gtfs regtopp)
  attr_accessor :rule_parameter_set_id, :referential_id, :user_id, :user_name, :data_format, :resources, :name, :no_save, :keep_obsolete_lines

  validates_presence_of :referential_id
  validates_presence_of :resources
  validates_presence_of :user_id
  validates_presence_of :user_name
  validates_presence_of :name

  validate :validate_file_size, :validate_file_content

  def initialize( params = {} )
    params.each {|k,v| send("#{k}=",v)}
  end

  def referential
    Referential.find(referential_id)
  end

  def organisation
    referential.organisation
  end

  def rule_parameter_set
    organisation.rule_parameter_sets.find(rule_parameter_set_id) if rule_parameter_set_id.present?
  end

  def save
    if valid?
      # Save resources
      save_resources

      # Call Iev Server
      begin
        Ievkitdeprecated.create_job(referential.slug, "importer", data_format, {
                            :file1 => params_io,
                            :file2 => transport_data_io
                          }

                         )

        # Delete resources
        delete_resources
      rescue Exception => exception
        # If iev server has an error must delete resources before
        delete_resources

        raise exception
      end
      true
    else
      false
    end
  end

  def params
    {}.tap do |h|
      h["parameters"] = validation_params ? action_params.merge(validation_params) : action_params
    end
  end

  def action_params
    {}
  end

  def validation_params
    {
      "validation" => rule_parameter_set.parameters
    } if rule_parameter_set.present?
  end

  def self.data_formats
    self.data_format.values.select{ |format| !ENV['deactivate_formats_import'].to_s.split(',').map(&:strip).include?(format) }
  end

  def params_io
    file = StringIO.new( params.to_json )
    Faraday::UploadIO.new(file, "application/json", "parameters.json")
  end

  def transport_data_io
    file = File.new(saved_resources_path, "r")
    if ".zip".casecmp(file_extname) == 0
      Faraday::UploadIO.new(file, "application/zip", original_filename )
    elsif ".xml".casecmp(file_extname) == 0
      Faraday::UploadIO.new(file, "application/xml", original_filename )
    end
  end

  def save_resources
    FileUtils.mkdir_p root
    FileUtils.cp resources.path, saved_resources_path
  end

  def delete_resources
    FileUtils.rm saved_resources_path if File.exists? saved_resources_path
  end

  def original_filename
    resources.original_filename
  end

  def file_extname
    File.extname(original_filename) if original_filename
  end

  def saved_resources_path
    @saved_resources_path ||= "#{root}/#{Time.now.to_i}#{file_extname}"
  end

  @@maximum_file_size = 200.megabytes
  cattr_accessor :maximum_file_size

  def validate_file_size
    return unless resources.present? and resources.path.present? and File.exists? resources.path

    if File.size(resources.path) > maximum_file_size
      message = I18n.t("activemodel.errors.models.import_task.attributes.resources.maximum_file_size", file_size:   ActionController::Base.helpers.number_to_human_size(File.size(resources.path)), maximum_file_size: ActionController::Base.helpers.number_to_human_size(maximum_file_size))
      errors.add(:resources, message)
    end
  end

  @@valid_mime_types = {
    neptune: %w{application/zip application/xml},
    netex: %w{application/zip},
    gtfs: %w{application/zip  text/plain},
    regtopp: %w{application/zip},
    netexprofile: %w{application/zip}
  }
  cattr_accessor :valid_mime_types

  def validate_file_content
    return unless resources.present? and resources.path.present? and File.exists? resources.path

    mime_type = (File.open(resources.path) { |f| MimeMagic.by_magic f }).try :type
    expected_mime_types = valid_mime_types[data_format.to_sym]

    unless expected_mime_types.include? mime_type
      message = I18n.t("activemodel.errors.models.import_task.attributes.resources.invalid_mime_type", mime_type: mime_type)
      errors.add(:resources, message)
    end
  end

end

app/controllers/import_tasks_controller.rb
# coding: utf-8
class ImportTasksController < ChouetteController
  before_action :check_authorize, except: [:show, :index]

  defaults :resource_class => ImportTask

  respond_to :html, :only => [:new, :create]
  respond_to :js, :only => [:new, :create]
  belongs_to :referential

  def new
    @available_imports = available_imports
    begin
      new!
    rescue Ievkitdeprecated::Error, Faraday::Error => error
      logger.error("Iev failure : #{error.message}")
      flash[:error] = t('iev.exception.default')
      redirect_to referential_path(@referential)
    end
  end

  def create
    @available_imports = available_imports
    begin
      create! do |success, failure|
        success.html { redirect_to referential_imports_path(@referential) }
      end
    rescue Ievkitdeprecated::Error, Faraday::Error => error
      logger.error("Iev failure : #{error.message}")
      flash[:error] = t('iev.exception.default')
      redirect_to referential_path(@referential)
    end
  end

  protected

  def available_imports
    import_task_parameters = params[:import_task]

    if import_task_parameters.present?
      @available_imports = [
        import_task_parameters[:data_format] == "neptune" ? build_resource : NeptuneImport.new(:referential_id => @referential.id ),
        import_task_parameters[:data_format] == "netex_experimental" ? build_resource : NetexExperimentalImport.new(:referential_id => @referential.id ),
        import_task_parameters[:data_format] == "netex_france" ? build_resource : NetexFranceImport.new(:referential_id => @referential.id ),
        import_task_parameters[:data_format] == "gtfs" ? build_resource : GtfsImport.new(:referential_id => @referential.id )
      ]
    else
      @available_imports = [
        NeptuneImport.new(:referential_id => @referential.id ),
        NetexExperimentalImport.new(:referential_id => @referential.id ),
        NetexFranceImport.new(:referential_id => @referential.id ),
        GtfsImport.new(:referential_id => @referential.id )
      ]
    end
  end

  def build_resource
    @import_task ||= if params[:import_task].present?
                       import_task_parameters = params[:import_task]
                       case import_task_parameters[:data_format]
                       when "neptune"
                         NeptuneImport.new(import_task_parameters)
                       when "netex_experimental"
                         @import_task = NetexExperimentalImport.new(import_task_parameters)
                       when "netex_france"
                         @import_task = NetexFranceImport.new(import_task_parameters)
                       when "gtfs"
                         @import_task = GtfsImport.new(import_task_parameters)
                       end
                     else
                       @import_task = NeptuneImport.new
                     end
  end

end

app/views/import_tasks/_fields_gtfs_import.erb
<%= form.input :object_id_prefix, :input_html => { :value => @referential.prefix } %>
<%= form.input :max_distance_for_commercial , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.max_distance_for_commercial"), :value => 0 } %>
<%= form.input :ignore_last_word , :as => :boolean , :input_html => { :title => t("formtastic.titles.import_task.ignore_last_word"), :value => false }%>
<%= form.input :ignore_end_chars  , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.ignore_end_chars"), :value => 0 }%>
<%= form.input :max_distance_for_connection_link  , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.max_distance_for_connection_link"), :value => 0 }%>

app/views/import_tasks/_fields_gtfs_import.html.erb
<%= form.input :references_type, :as => :select, :include_blank => t("import_tasks.new.all"), :input_html => { :title => t("formtastic.titles.import_task.references_type") } %>
<%= form.input :object_id_prefix, :input_html => { :value => @referential.prefix } %>
<%= form.input :max_distance_for_commercial , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.max_distance_for_commercial"), :value => 0 } %>
<%= form.input :ignore_last_word , :as => :boolean , :input_html => { :title => t("formtastic.titles.import_task.ignore_last_word"), :value => false }%>
<%= form.input :ignore_end_chars  , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.ignore_end_chars"), :value => 0 }%>
<%= form.input :max_distance_for_connection_link  , :as => :number , :input_html => { :title => t("formtastic.titles.import_task.max_distance_for_connection_link"), :value => 0 }%>
<%= form.input :parse_interchanges  , :as => :boolean , :input_html => { :title => t("formtastic.titles.import_task.parse_interchanges") }%>
<%= form.input :parse_connection_links  , :as => :boolean , :input_html => { :title => t("formtastic.titles.import_task.parse_connection_links") }%>

app/views/import_tasks/_fields_netexprofile_import.html.erb
<%= form.input :object_id_prefix, :input_html => { :value => @referential.prefix } %>
<%= form.input :parse_site_frames, :as => :boolean, :input_html => { :checked => false, :disabled => !current_user.admin? } %>
<%= form.input :validate_against_schema, :as => :boolean, :input_html => { :checked => true, :disabled => !current_user.admin? } %>
<%= form.input :validate_against_profile, :as => :boolean, :input_html => { :checked => true, :disabled => !current_user.admin? } %>
<%= form.input :continue_on_line_errors, :as => :boolean, :input_html => { :checked => false } %>

app/views/import_tasks/_fields_regtopp_import.html.erb
<%= form.input :references_type, :as => :select, :include_blank => t("import_tasks.new.all"), :input_html => { :title => t("formtastic.titles.import_task.references_type") } %>
<%= form.input :object_id_prefix, :input_html => { :value => @referential.prefix } %>
<%= form.input :coordinate_projection, :as => :select, :include_blank => false, :collection => RegtoppImport.available_srids, :selected  => "EPSG:"+@referential.projection_type %>
<%= form.input :version, :as => :select, :collection => RegtoppImport.available_versions%>
<%= form.input :charset_encoding, :as => :select, :collection => RegtoppImport.charset_encoding%>
<%= form.input :calendar_strategy, :as => :select, :collection => RegtoppImport.calendar_strategy%>
<%= form.input :batch_parse, :as => :boolean, :input_html => { :checked => true } %>

app/views/import_tasks/new.html.erb
<%= title_tag t(".title") %>

<ul class="nav nav-pills">
  <% ImportTask.data_formats.each do |format| %>
    <li role="presentation">
      <a href="#<%= format %>" class='<%= @import_task.data_format == format ? "#{format} active" : "#{format}" %>'
                               title='<%= t(:"enumerize.data_format_detail.#{format}")%>'
                               data-toggle="tab"><%= t(:"enumerize.data_format.#{format}") %>
      </a>
    </li>
  <% end %>
</ul>

<div class="tab-content">
  <% @available_imports.each do |import_task| %>
    <%= semantic_form_for [@referential, import_task], :as => :import_task, :url => referential_import_tasks_path(@referential),
                          :namespace => import_task.data_format, :html => { :id => "#{import_task.data_format}",
                                                                            :class => "tab-pane highlight" } do |form| %>
      <%= form.inputs do %>
        <%= form.input :user_name, :as => :hidden, :input_html => { :value => current_user.name } %>
        <%= form.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
        <%= form.input :data_format, :as => :hidden %>
        <%= form.input :referential_id, :as => :hidden, :input_html => { :value => @referential.id } %>
        <%= form.input :name %>
        <%= form.input :no_save, :as => :boolean %>
        <%= form.input :keep_obsolete_lines, :as => :boolean, :input_html => { :checked => true }%>
        <%= form.input :rule_parameter_set_id, :as => :select,
                       :collection =>  @referential.organisation.rule_parameter_sets.map { |rps| [ rps.name, rps.id ] },
                       :include_blank => true %>
        <%= form.input :resources, :as => :file %>
      <% end %>
      <%= render partial: "fields_#{import_task.data_format}_import", :locals => { :form => form } %>
      <%= form.actions do %>
        <%= form.action :submit, :as => :button , :label => t( 'formtastic.import' ) %>
        <%= form.action :cancel, :as => :link %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%= javascript_include_tag new_referential_import_task_path(@referential, :format => :js) %>