config/routes.rb
ChouetteIhm::Application.routes.draw do

  # ====> Beware not to use /healtcheck route : already used by MiddlewareHealthcheck

  devise_for :users, :controllers => {
    :registrations => 'users/registrations', :invitations => 'users/invitations',
    :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  devise_scope :user do
    authenticated :user do
      root :to => 'referentials#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      get '/additionnal_fields', to: 'users#additionnal_fields'
      post '/save_additionnal_fields', to: 'users#save_additionnal_fields'
    end
    
  end

  namespace :api do
    namespace :v1 do
      resources :time_tables, :only => [:index, :show]
      resources :connection_links, :only => [:index, :show]
      resources :companies, :only => [:index, :show]
      resources :networks, :only => [:index, :show]
      resources :stop_areas, :only => [:index, :show]
      resources :group_of_lines, :only => [:index, :show]
      resources :access_points, :only => [:index, :show]
      resources :access_links, :only => [:index, :show]
      resources :lines, :only => [:index, :show] do
        resources :journey_patterns, :only => [:index, :show]
        resources :routes, :only => [:index, :show] do
          resources :vehicle_journeys, :only => [:index, :show]
          resources :journey_patterns, :only => [:index, :show]
          resources :stop_areas, :only => [:index, :show]
        end
      end
      resources :routes, :only => :show
      resources :journey_patterns, :only => :show
      resources :vehicle_journeys, :only => :show
    end
  end

  resource :organisation, :only => [:show, :edit, :update] do
    resources :users
    get '/role/edit/:id', to: 'users#role_edit', as: 'user_role_edit'
    patch '/role/update/:id', to: 'users#role_update', as: 'user_role_update'
    resources :rule_parameter_sets
  end

  resources :referentials do
    resources :api_keys
    resources :autocomplete_stop_areas
    resources :autocomplete_time_tables
    resources :autocomplete_route_sections
    resources :autocomplete_timebands
    resources :group_of_lines do
      collection do
        get 'name_filter'
      end
    end

    resources :networks

    resources :lines do
      delete :index, on: :collection, action: :delete_all
      collection do
        get 'name_filter'
      end
      resources :routes do
        member do
          get 'edit_boarding_alighting'
          put 'save_boarding_alighting'
        end
        resources :journey_patterns do
          member do
            get 'new_vehicle_journey'
          end
          resource :route_sections_selector, path: 'sections' do
            post 'selection'
          end
        end
        resources :vehicle_journeys, :vehicle_journey_frequencies do
          get 'select_journey_pattern', :on => :member
          resources :vehicle_translations
          resources :time_tables
        end
        resources :vehicle_journey_imports
        resources :vehicle_journey_exports
      end
    end

    resources :import_tasks, :only => [:new, :create]
    resources :imports, :only => [:index, :show, :destroy] do
      member do
        get "imported_file"
        get "rule_parameter_set"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :export_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :exports, :only => [:index, :show, :destroy]  do
      member do
        get "exported_file"
        get "compliance_check"
        get 'progress'
        get 'export', defaults: { format: 'zip' }
      end
    end

    resources :compliance_check_tasks, :only => [:new, :create] do
      collection do
        get 'references'
      end
    end

    resources :compliance_checks, :only => [:index, :show, :destroy] do
      member do
        get 'export', defaults: { format: 'zip' }
        get 'report'
        get 'progress'
        get 'rule_parameter_set'
        get 'download_validation'
      end
      collection do
        get 'references'
      end
    end

    resources :companies

    resources :time_tables do
      collection do
        get :tags
      end
      member do
        get 'duplicate'
      end
      resources :time_table_dates
      resources :time_table_periods
      resources :time_table_combinations
    end

    resources :timebands

    resources :access_points do
       resources :access_links
    end

    resources :stop_areas do
      resources :access_points do
        resources :access_links
      end
      resources :stop_area_copies
      resources :stop_area_routing_lines
      member do
        get 'add_children'
        get 'select_parent'
        get 'add_routing_lines'
        get 'add_routing_stops'
        get 'access_links'
      end
      collection do
        put 'default_geometry'
      end
    end

    resources :connection_links do
      resources :stop_areas
      member do
        get 'select_areas'
      end
    end
    resources :clean_ups

    resources :route_sections do
      collection  do
        get 'create_to_edit'
      end
    end
  end
  root :to => "referentials#index"

  get '/statistics', :to => 'statistics#index'
  get '/statistics/export', :to => 'statistics#export'

  get '/help/(*slug)' => 'help#show'

  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#server_error'
  get '/500', :to => 'errors#server_error'

end

app/models/compliance_check.rb
class ComplianceCheck
  include JobConcern

  def initialize( response )
    @datas = response
  end

  def report?
    links["action_report"].present?
  end

  def report
    Rails.cache.fetch("#{cache_key}/action_report", expires_in: cache_expiration) do
      if report_path = links["action_report"]
        ComplianceCheckReport.new Ievkitdeprecated.get(report_path)
      end
    end
  end

  def compliance_check_validation_report?
    links["validation_report"].present?
  end

  def compliance_check_validation_report
    Rails.cache.fetch("#{cache_key}/validation_report", expires_in: cache_expiration) do
      if report_path = links["validation_report"]
        ComplianceCheckResult.new Ievkitdeprecated.get(report_path)
      end
    end
  end

  def rule_parameter_set?
    links["validation_params"].present?
  end

  def rule_parameter_set
    Rails.cache.fetch("#{cache_key}/validation_params", expires_in: cache_expiration) do
      if rule_parameter_set_path = links["validation_params"]
        response = Ievkitdeprecated.get(rule_parameter_set_path)
        RuleParameterSet.new(name: '', compliance_check: self).tap do |rps|
          rps.parameters = response.validation
        end
      end
    end
  end

  def destroy
    if delete_path =  links["delete"]
      Ievkitdeprecated.delete(delete_path)
    elsif cancel_path = links["cancel"]
      Ievkitdeprecated.delete(cancel_path)
    end
  end

  def format
    datas.type
  end
end

app/controllers/compliance_checks_controller.rb
class ComplianceChecksController < ChouetteController
  before_action :check_authorize, except: [:show, :index, :report, :download_validation, :rule_parameter_set, :export]

  helper IevkitViews::Engine.helpers
  defaults :resource_class => ComplianceCheck

  respond_to :html, :js
  respond_to :zip, :only => :export
  belongs_to :referential

  def index
    begin
      index! do
        build_breadcrumb :index
      end
    rescue Ievkitdeprecated::Error, Faraday::Error => error
      logger.error("Iev failure : #{error.message}")
      flash[:error] = t(error.locale_for_error)
      redirect_to referential_path(@referential)
    end
  end

  def show
    if resource.report?
      redirect_to report_referential_compliance_check_path(@referential.id, resource.id)
    else
      begin
        show! do |format|
          build_breadcrumb :show
        end
      rescue Ievkitdeprecated::Error, Faraday::Error => error
        logger.error("Iev failure : #{error.message}")
        flash[:error] = t(error.locale_for_error)
        redirect_to referential_path(@referential)
      end
    end
  end

  def progress
    @job = IevkitJob.new(@referential, resource)
    render json: @job.is_terminated? ? { redirect:  compliance_check_referential_import_path(@referential.id, resource.id) } : @job.progress_steps
  end

  def report
    @job = IevkitJob.new(@referential, resource)
    @job.search = params[:q][:search] if params[:q]
    @transport_datas_selected = params[:type_td]
    @default_view = params[:default_view] ? params[:default_view].to_sym : :tests
    @download_page = download_validation_referential_compliance_check_path(
      default_view: @default_view, referential_id: @referential.id, id: resource.id)
    @result, @datas, @sum_report, @errors = @job.send("#{@default_view}_views", (@transport_datas_selected != 'all' ? @transport_datas_selected : nil ))
    @elements_to_paginate = Kaminari.paginate_array(@datas)
                                    .page(params[:page])

    build_breadcrumb :report
  end

  def download_validation
    @job = IevkitJob.new(@referential, resource)
    datas, args = @job.download_validation_report(params[:default_view])
    send_data datas, args
  end

  def references
    @references = referential.send(params[:type]).where("name ilike ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json do
        render json: @references.collect { |child| { id: child.id, name: child.name } }
      end
    end
  end

  def rule_parameter_set
    begin
      @rule_parameter_set = resource.rule_parameter_set
      build_breadcrumb :rule_parameter_set
      render "rule_parameter_sets/show"
    rescue Ievkitdeprecated::Error, Faraday::Error => error
      logger.error("Iev failure : #{error.message}")
      flash[:error] = t(error.locale_for_error)
      redirect_to referential_path(@referential)
    end
  end

  def export
    respond_to do |format|
      format.zip { send_file ComplianceCheckExport.new(resource, @referential.id, request).export, :type => :zip }
    end
  end

  protected

  alias_method :compliance_check, :resource

  def compliance_check_service
    ComplianceCheckService.new(@referential)
  end

  def resource
    @compliance_check ||= compliance_check_service.find(params[:id])
    return @compliance_check unless @compliance_check.report
    @line_items = @compliance_check.report.line_items
    if @line_items.size > 500
      @line_items = Kaminari.paginate_array(@line_items).page(params[:page])
    end
    @compliance_check
  end

  def collection
    @compliance_checks ||= Kaminari.paginate_array(compliance_check_service.all.sort_by{ |compliance_check|
        compliance_check.created_at
      }.reverse).page(params[:page])
  end

end

app/helpers/compliance_checks_helper.rb
# -*- coding: utf-8 -*-
module ComplianceChecksHelper

  def fields_for_compliance_check_format(form)
    begin
      render :partial => compliance_check_partial_name(form), :locals => { :form => form }
    rescue ActionView::MissingTemplate
      ""
    end
  end

  def compliance_check_partial_name(form)
    "fields_#{form.object.format.underscore}_compliance_check"
  end

  def compliance_icon( compliance_check)
    return nil unless compliance_check.compliance_check_validation_report
    compliance_check.compliance_check_validation_report.tap do |cct|
      if cct.failed? || cct.any_error_severity_failure?
        return 'icons/link_page_alert.png'
      else
        return 'icons/link_page.png'
      end
    end
  end

  def status_icon( compliance_check_result_status, compliance_check_result_severity )
    if compliance_check_result_status == "uncheck"
      ("<i class='fa fa-ban status_" + compliance_check_result_status + "_" + compliance_check_result_severity  + "'></i>").html_safe
    elsif compliance_check_result_status == "ok"
      ("<i class='fa fa-check status_" + compliance_check_result_status + "_" + compliance_check_result_severity + "'></i>").html_safe
    else
      ("<i class='fa fa-times status_" + compliance_check_result_status + "_" + compliance_check_result_severity  + "'></i>").html_safe
    end
  end

  def test_definition (compliance_check_result_code)
    Rails.application.config.validation_spec + I18n.locale.to_s + "/" + compliance_check_result_code +".html"
  end

  def object_url (referential_id, error)
    location = "/referentials/#{referential_id}"
    object_path = error[:source][:object_path]
    object_path.delete_at(1) if object_path.first['type'] == "vehicle_journey"
    types, identifiers = object_path.reverse.map { |resource| [ resource['type'], resource['id'] ] }.transpose
    method_name = (['referential'] + types + ['path']).join('_')
    identifiers.unshift referential_id
    return identifiers.include?(nil) ? false : (send(method_name, *identifiers))
  rescue => e
    Rails.logger.error "Error: #{e.message}"
  end

  def object_labels_hash (error)
    ### THE error HASH STRUCTURE
    # 1. error[:source]
    #      0..1 file
    #           1 filename
    #           0..1 line_number
    #           0..1 column_number
    #      0..1 objectid
    #      0..1 label
    #      0..  object_path
    #           1 type
    #           1 id
    # 0.. error[:target]
    # 0..1 error[:error_value]
    # 0..1 error[:reference_value]
    object_labels_hash = Hash.new
    object_labels_hash[:source_objectid] = error[:source].objectid if error[:source].objectid.present?
    object_labels_hash[:source_label] = error[:source].label if error[:source].label.present?
    if error[:source].file.present?
      object_labels_hash[:filename] = error[:source].file.filename
      object_labels_hash[:line_number] = error[:source].file.line_number if error[:source].file.line_number.present?
      object_labels_hash[:column_number] = error[:source].file.column_number if error[:source].file.column_number.present?
    end

    if error[:target].present?
      error[:target].each_with_index do |target, index|
        object_labels_hash["target_#{index}_objectid".to_sym] = target[:objectid] if target[:objectid]
        object_labels_hash["target_#{index}_label".to_sym] = target[:label] if target[:label]
      end
    end

    object_labels_hash[:error_value] = error[:error_value].present? ? error[:error_value] : ''
    object_labels_hash[:reference_value] = error[:reference_value].present? ? error[:reference_value] : ''
    object_labels_hash[:error_description] = error[:error_description].present? ? error[:error_description] : ''
    object_labels_hash[:error_value] = error[:error_value].present? ? error[:error_value] : ''

    object_labels_hash
  end


end

app/views/compliance_checks/_compliance_check.html.erb
<div id="index_item" class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title clearfix">
      <% if policy(:application).write? %>
        <span class="pull-right">
          <%= link_to referential_compliance_check_path(@referential, compliance_check.id), :method => :delete, :data => {:confirm =>  t('compliance_checks.actions.destroy_confirm')}, :class => "btn btn-danger btn-sm" do %>
            <span class="fa fa-trash-o"></span>
          <% end %>
        </span>
      <% end %>
      <h5>
        <%= link_to( referential_compliance_check_path(@referential, compliance_check.id), :class => "preview", :title => "#{ComplianceCheck.model_name.human.capitalize} #{compliance_check.name}") do %>
	  <%= job_status_title(compliance_check) %>
        <% end %>
      </h5>
    </div>
  </div>
  <div class="panel-body">
    <p><%= link_to( font_awesome_classic_tag("fa-external-link") + t("compliance_checks.actions.report"), report_referential_compliance_check_path(@referential, compliance_check.id)) if compliance_check.report? %></p>
  </div>
  <div class="panel-footer">
    <div class="history">
      <%= l compliance_check.created_at, :format => "%d/%m/%Y %H:%M" %> | <%= compliance_check.user_name %>
    </div>
  </div>
</div>

app/views/compliance_checks/_compliance_check_results.erb
<p>
<form class="form-inline">
  <div class="form-group">
    <label><%= t("shared.ie_report.search") %></label>
    <input id="filter" type="text" class="form-control">
  </div>
  <div class="form-group">
    <label><%=ComplianceCheckResult.human_attribute_name(:severity)%></label>
    <select class="filter-severity form-control">
      <option></option>
      <option value="severity-error"><%= t("compliance_check_results.severities.error") %></option>
      <option value="severity-warning"><%= t("compliance_check_results.severities.warning") %></option>
    </select>
  </div>
  <div class="form-group">
    <label><%=ComplianceCheckResult.human_attribute_name(:status)%></label>
    <select class="filter-status form-control">
      <option></option>
      <option value="status-ok"><%= t("compliance_check_results.statuses.ok") %></option>
      <option value="status-nok"><%= t("compliance_check_results.statuses.nok") %></option>
      <option value="status-uncheck"><%= t("compliance_check_results.statuses.uncheck") %></option>
    </select>
  </div>
</form>
</p>
<table class="table table-hover toggle-circle toggle-medium"
       data-filter="#filter"
       data-page-size="20"
       data-title-nok="<%=t('compliance_check_results.statuses.nok') %>"
       data-title-uncheck="<%=t('compliance_check_results.statuses.uncheck') %>"
       data-title-ok="<%=t('compliance_check_results.statuses.ok') %>">
  <thead>
    <tr>
      <th data-sort-ignore="true"><%= ComplianceCheckResult.human_attribute_name(:status) %></th>
      <th class="col-md-1" data-sort-ignore="true"><%= ComplianceCheckResult.human_attribute_name(:severity) %></th>
      <th class="col-md-3"><%= ComplianceCheckResult.human_attribute_name(:rule_code) %></th>
      <th class="col-md-2"><%=t('compliance_check_results.errors') %></th>
      <th class="col-md-6" data-toggle="true" data-sort-ignore="true"><%= ComplianceCheckResult.human_attribute_name(:detail) %></th>
      <th data-hide="all" data-sort-ignore="true"></th>
    </tr>
  </thead>
  <tbody>
    <% if compliance_check_validation_report %>
      <% compliance_check_validation_report.tests.each_with_index do |test, index| %>
      <tr class='<%= "#{test.result}_#{test.severity}" %>'>
        <td data-value="<%="status-#{test.result}"%>"><%= status_icon( test.result, test.severity ) %> </td>
        <td data-value="<%="severity-#{test.severity}"%>"><%= t("compliance_check_results.severities.#{test.severity}_txt") %></td>
        <td data-value="<%= "#{test.result}_#{test.severity}" %>">
          <%= link_to test.test_id, test_definition(test.test_id), title: ComplianceCheckResult.human_attribute_name(test.test_id), target: "compliance_check" %>
        </td>
        <td>
          <%= ("#{test.error_count || 0} #{ComplianceCheckResult.human_attribute_name(:violation_count)}") if test.errors.present? %>
        </td>
        <td>
          <%= truncate(t("activemodel.attributes.compliance_check_result.#{test.test_id}"), length: 50)%>
        </td>
        <td>
          <p><b><%=t("activemodel.attributes.compliance_check_result.#{test.test_id}")%></b></p>
          <% if test.errors.present? %>
            <% test.errors.first(10).each do |error| %>
              <dl class="inline">
              <dt>
                <% if error["source"].present? %>
                  <% if error[:source].object_path.present? %>
                    <% if error[:source].label.present? %>
                      <%= link_to error[:source].label, object_url(@referential.id, error), target: :_blank %>
                    <% else %>
                      <%= link_to "#{error[:source].object_path.type} (#{error[:source].object_path.id})", object_url(@referential.id, error), target: :_blank %>
                    <% end %>
                  <% end %>
                  <% if error[:source].file.present? %>
                    <%= error[:source].objectid if error[:source].objectid.present? %>
                  <% end %>
                <% end %>
              </dt>
              <dd><%=t("compliance_check_results.details.detail_#{error[:error_id]}", object_labels_hash(error))%></dd>
              </dl>
              <% if error[:source].file.present? %>
                <p class="file_error">
                <%= error[:source].file.filename  %>
                  <%= ", li: #{error[:source].file.line_number}" if error[:source].file.line_number.present?  %>
                  <%= ", co: #{error[:source].file.column_number}" if error[:source].file.column_number.present?  %>
                </p>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="6"><%= t('compliance_check_results.in_progress') %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot class="hide-if-no-paging">
    <tr>
      <td colspan="5"><ul class="pagination pagination-centered"></ul></td>
    </tr>
  </tfoot>
</table>

app/views/compliance_checks/_compliance_checks.html.erb
<div class="page_info">
  <span class="search"> <%= t("will_paginate.page_entries_info.search") %></span> <%= page_entries_info @compliance_checks %>
</div>
<div class="compliance_checks paginated_content">
  <%= paginated_content @compliance_checks, "compliance_checks/compliance_check" %>
</div>
<%= render 'shared/paginate', { datas: @compliance_checks } %>

app/views/compliance_checks/detailed_errors_index.csv.erb
<%= I18n.t("activemodel.attributes.compliance_check_result.severity") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.rule_code") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.object") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.resource") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.title") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.detail") %>
<% @compliance_check.compliance_check_validation_report.tests.each do |r| %><% if r.errors.present? %><% r.errors.first(10).each do |error| %><% case  r.severity %><% when "warning" %><%= I18n.t "compliance_check_results.severities.warning_txt" %><% when "error" %><%= I18n.t "compliance_check_results.severities.error_txt" %><% end %>;<%= r.test_id %>;<% if error["source"].present? %><%= error["source"]["objectid"] if error["source"]["objectid"].present? %>;<% if error["source"]["object_path"].present? %><%= object_url(@referential_id, error) %><% elsif error["source"]["file"].present? %><%= File.basename(error["source"]["file"]["filename"]) +" - " %><%= I18n.t "compliance_check_results.index.column" %>:<%= error["source"]["file"]["column_number"] %>,<%= I18n.t "compliance_check_results.index.line" %>:<%= error["source"]["file"]["line_number"] %><% end %>;<% else %>;;<% end %><%= I18n.t("activemodel.attributes.compliance_check_result."+r.test_id) %>;<%= I18n.t("compliance_check_results.details.detail_" + error["error_id"], object_labels_hash(error) )%><%= "\n" %><% end %><% end %><% end %>

app/views/compliance_checks/index.html.erb
<%= title_tag t('.title') %>
<div class="warning"><%= t('.warning') %> </div>

<div id="compliance_checks"><%= render 'compliance_checks' %></div>

<% content_for :sidebar do %>
<ul class="actions">
  <li><%= link_to t('compliance_check_tasks.actions.new'), new_referential_compliance_check_task_path(), :class => "add" %></li>
  <li><%= link_to t('rule_parameter_sets.actions.index'), organisation_rule_parameter_sets_path, :class => "link" %></li>
</ul>
<% end %>

app/views/compliance_checks/index.js.erb
$('#compliance_checks').html('<%= escape_javascript(render("compliance_checks")) %>');

app/views/compliance_checks/report.html.erb
<% if @compliance_check and @compliance_check.report.failure_code? %>
    <p>
    <span class="name aborted">Something unexpected happened. It could be a temporary situation and restarting the job manually may solve the problem.
      Please contact the system administrator if retry results in the same error.</span>

    <div><%= t('.code') %>:        <%= @compliance_check.report.datas.failure.code %></div>
    <div><%= t('.description') %>: <%= @compliance_check.report.datas.failure.description %></div>

    </p>
<% else %>
<%= render 'ievkit_views/report' %>



<% if false %>
<%= title_tag job_status_title(@compliance_check) %>

<div class="compliance_check_show">
  <div class="links">
    <% if @compliance_check.class == Import %>
      <%= link_to(font_awesome_classic_tag('fa-eye') + t("compliance_checks.report.action_report"), referential_import_path(@referential, @compliance_check.id)) %>
      <%= link_to font_awesome_classic_tag("fa-external-link") + t("compliance_checks.rule_parameter_set"), rule_parameter_set_referential_import_path(@referential, @compliance_check.id) if @compliance_check.rule_parameter_set? %>
    <% elsif @compliance_check.class == Export %>
      <%= link_to(font_awesome_classic_tag('fa-eye') + t("compliance_checks.report.action_report"), referential_export_path(@referential, @compliance_check.id)) %>
      <%= link_to font_awesome_classic_tag("fa-external-link") + t("compliance_checks.rule_parameter_set"), rule_parameter_set_referential_export_path(@referential, @compliance_check.id) if @compliance_check.rule_parameter_set? %>
    <% else %>
      <%= link_to(font_awesome_classic_tag('fa-eye') + t("compliance_checks.report.action_report"), referential_compliance_check_path(@referential, @compliance_check.id)) %>
      <%= link_to font_awesome_classic_tag("fa-external-link") + t("compliance_checks.rule_parameter_set"), rule_parameter_set_referential_compliance_check_path(@referential, @compliance_check.id) if @compliance_check.rule_parameter_set? %>
    <% end %>
    <div class="btn-group pull-right">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <%= t("compliance_checks.show.export") %> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <% if @compliance_check.class == Import %>
            <%= link_to t("compliance_checks.show.export_csv"), export_referential_import_path(@referential, @compliance_check.id) %>
          <% elsif @compliance_check.class == Export %>
            <%= link_to t("compliance_checks.show.export_csv"), export_referential_export_path(@referential, @compliance_check.id) %>
          <% else %>
            <%= link_to t("compliance_checks.show.export_csv"), export_referential_compliance_check_path(@referential, @compliance_check.id) %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="report" data-refresh-interval="<%= job_refresh_interval(@compliance_check) %>">
    <%= render :partial => "compliance_checks/compliance_check_results", locals: { compliance_check_validation_report: @compliance_check.compliance_check_validation_report } %>
  </div>
</div>

<% content_for :sidebar do %>
  <% if @compliance_check.compliance_check_validation_report && @compliance_check.compliance_check_validation_report.nok_error.blank? %>
    <div class="row">
      <%=font_awesome_classic_tag('fa-thumbs-up fa-5x col-md-3')%>
      <p class='col-md-7' id='validation_success'><%=t('.validation_success')%></p>
    </div>
  <% end %>
  <ul class="actions">
    <li>
      <% unless [Import, Export].include? @compliance_check.class %>
        <%= link_to  t('compliance_checks.actions.destroy'), referential_compliance_check_path(@referential, @compliance_check.id),
                     :method => :delete,  :data => {:confirm =>  t('compliance_checks.actions.destroy_confirm')},
                     :class => "remove" %>
      <% end %>
    </li>
  </ul>
  <%= history_tag(@compliance_check) %>
  <div id="error" class="graph"></div>
  <div id="warning" class="graph"></div>
<% end %>
<% end %>
<% end %>

app/views/compliance_checks/show.html.erb
<div class="test">
  <%= title_tag job_status_title(@compliance_check) %>
</div>

<%= render 'ievkit_views/progress_bar', {
        path_to_progress_job: progress_referential_compliance_check_path(@referential, @compliance_check.id, format: :js) 
      } %>

<% content_for :sidebar do %>
  <ul class="actions">
    <li><%= link_to t('compliance_checks.actions.destroy'), referential_compliance_check_path(@referential, @compliance_check.id), method: :delete, data: {confirm: t('compliance_checks.actions.destroy_confirm')}, class: "remove" %></li>
  </ul>

  <%= history_tag(@compliance_check) %>

<% end %>

app/views/compliance_checks/summary_errors_index.csv.erb
<%= I18n.t("activemodel.attributes.compliance_check_result.severity") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.status") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.rule_code") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.title") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.url") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.violation_count_txt") %>;<%= I18n.t("activemodel.attributes.compliance_check_result.objects") %>
<% @compliance_check.compliance_check_validation_report.tests.each do |r| %><% case  r.severity %><% when "warning" %><%= I18n.t "compliance_check_results.severities.warning_txt" %><% when "error" %><%= I18n.t "compliance_check_results.severities.error_txt" %><% end %>;<%= r.result %>;<%= r.test_id %>;<%= I18n.t("activemodel.attributes.compliance_check_result."+r.test_id) %>;<%= Rails.application.config.validation_spec + I18n.locale.to_s + "/" + r.test_id + ".html" %>;<%= r.error_count %><% if r.error_count > 0 %><% if r.errors.present? %>;<% r.errors.first(10).each do |error| %><% if error["source"] %><%= error["source"]["objectid"] + " " %><% else %><%= " " %><% end %><% end %><% end %><% end %>
<% end %>